#########################################################
# This file has been automatically generated by gem2tgz #
#########################################################
# -*- encoding: utf-8 -*-
# stub: hoe 3.22.1 ruby lib

Gem::Specification.new do |s|
  s.name = "hoe".freeze
  s.version = "3.22.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.4".freeze) if s.respond_to? :required_rubygems_version=
  s.metadata = { "bug_tracker_uri" => "https://github.com/seattlerb/hoe/issues", "changelog_uri" => "https://github.com/seattlerb/hoe/blob/master/History.rdoc", "documentation_uri" => "http://docs.seattlerb.org/hoe/Hoe.pdf", "homepage_uri" => "http://www.zenspider.com/projects/hoe.html", "source_code_uri" => "https://github.com/seattlerb/hoe" } if s.respond_to? :metadata=
  s.require_paths = ["lib".freeze]
  s.authors = ["Ryan Davis".freeze]
  s.cert_chain = ["-----BEGIN CERTIFICATE-----\nMIIDPjCCAiagAwIBAgIBBDANBgkqhkiG9w0BAQsFADBFMRMwEQYDVQQDDApyeWFu\nZC1ydWJ5MRkwFwYKCZImiZPyLGQBGRYJemVuc3BpZGVyMRMwEQYKCZImiZPyLGQB\nGRYDY29tMB4XDTE5MTIxMzAwMDIwNFoXDTIwMTIxMjAwMDIwNFowRTETMBEGA1UE\nAwwKcnlhbmQtcnVieTEZMBcGCgmSJomT8ixkARkWCXplbnNwaWRlcjETMBEGCgmS\nJomT8ixkARkWA2NvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALda\nb9DCgK+627gPJkB6XfjZ1itoOQvpqH1EXScSaba9/S2VF22VYQbXU1xQXL/WzCkx\ntaCPaLmfYIaFcHHCSY4hYDJijRQkLxPeB3xbOfzfLoBDbjvx5JxgJxUjmGa7xhcT\noOvjtt5P8+GSK9zLzxQP0gVLS/D0FmoE44XuDr3iQkVS2ujU5zZL84mMNqNB1znh\nGiadM9GHRaDiaxuX0cIUBj19T01mVE2iymf9I6bEsiayK/n6QujtyCbTWsAS9Rqt\nqhtV7HJxNKuPj/JFH0D2cswvzznE/a5FOYO68g+YCuFi5L8wZuuM8zzdwjrWHqSV\ngBEfoTEGr7Zii72cx+sCAwEAAaM5MDcwCQYDVR0TBAIwADALBgNVHQ8EBAMCBLAw\nHQYDVR0OBBYEFEfFe9md/r/tj/Wmwpy+MI8d9k/hMA0GCSqGSIb3DQEBCwUAA4IB\nAQCkkcHqAa6IKLYGl93rn78J3L+LnqyxaA059n4IGMHWN5bv9KBQnIjOrpLadtYZ\nvhWkunWDKdfVapBEq5+T4HzqnsEXC3aCv6JEKJY6Zw7iSzl0M8hozuzRr+w46wvT\nfV2yTN6QTVxqbMsJJyjosks4ZdQYov2zdvQpt1HsLi+Qmckmg8SPZsd+T8uiiBCf\nb+1ORSM5eEfBQenPXy83LZcoQz8i6zVB4aAfTGGdhxjoMGUEmSZ6xpkOzmnGa9QK\nm5x9IDiApM+vCELNwDXXGNFEnQBBK+wAe4Pek8o1V1TTOxL1kGPewVOitX1p3xoN\nh7iEjga8iM1LbZUfiISZ+WrB\n-----END CERTIFICATE-----\n".freeze]
  s.date = "2020-02-13"
  s.description = "Hoe is a rake/rubygems helper for project Rakefiles. It helps you\nmanage, maintain, and release your project and includes a dynamic\nplug-in system allowing for easy extensibility. Hoe ships with\nplug-ins for all your usual project tasks including rdoc generation,\ntesting, packaging, deployment, and announcement.\n\nSee class rdoc for help. Hint: `ri Hoe` or any of the plugins listed\nbelow.\n\nFor extra goodness, see: http://docs.seattlerb.org/hoe/Hoe.pdf".freeze
  s.email = ["ryand-ruby@zenspider.com".freeze]
  s.executables = ["sow".freeze]
  s.extra_rdoc_files = ["History.rdoc".freeze, "Manifest.txt".freeze, "README.rdoc".freeze]
  s.files = [".autotest".freeze, "History.rdoc".freeze, "Hoe.pdf".freeze, "Manifest.txt".freeze, "README.rdoc".freeze, "Rakefile".freeze, "bin/sow".freeze, "lib/hoe.rb".freeze, "lib/hoe/clean.rb".freeze, "lib/hoe/compiler.rb".freeze, "lib/hoe/debug.rb".freeze, "lib/hoe/deps.rb".freeze, "lib/hoe/flay.rb".freeze, "lib/hoe/flog.rb".freeze, "lib/hoe/gem_prelude_sucks.rb".freeze, "lib/hoe/gemcutter.rb".freeze, "lib/hoe/inline.rb".freeze, "lib/hoe/newb.rb".freeze, "lib/hoe/package.rb".freeze, "lib/hoe/publish.rb".freeze, "lib/hoe/racc.rb".freeze, "lib/hoe/rake.rb".freeze, "lib/hoe/rcov.rb".freeze, "lib/hoe/rdoc.rb".freeze, "lib/hoe/signing.rb".freeze, "lib/hoe/test.rb".freeze, "lib/minitest/test_task.rb".freeze, "template/.autotest.erb".freeze, "template/History.txt.erb".freeze, "template/Manifest.txt.erb".freeze, "template/README.txt.erb".freeze, "template/Rakefile.erb".freeze, "template/bin/file_name.erb".freeze, "template/lib/file_name.rb.erb".freeze, "template/test/test_file_name.rb.erb".freeze, "test/test_hoe.rb".freeze, "test/test_hoe_debug.rb".freeze, "test/test_hoe_gemcutter.rb".freeze, "test/test_hoe_package.rb".freeze, "test/test_hoe_publish.rb".freeze, "test/test_hoe_test.rb".freeze]
  s.homepage = "http://www.zenspider.com/projects/hoe.html".freeze
  s.licenses = ["MIT".freeze]
  s.rdoc_options = ["--main".freeze, "README.rdoc".freeze]
  s.required_ruby_version = Gem::Requirement.new("~> 2.1".freeze)
  s.rubygems_version = "2.5.2.1".freeze
  s.summary = "Hoe is a rake/rubygems helper for project Rakefiles".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>.freeze, ["< 15.0", ">= 0.8"])
      s.add_development_dependency(%q<rdoc>.freeze, ["< 7", ">= 4.0"])
    else
      s.add_dependency(%q<rake>.freeze, ["< 15.0", ">= 0.8"])
      s.add_dependency(%q<rdoc>.freeze, ["< 7", ">= 4.0"])
    end
  else
    s.add_dependency(%q<rake>.freeze, ["< 15.0", ">= 0.8"])
    s.add_dependency(%q<rdoc>.freeze, ["< 7", ">= 4.0"])
  end
end
